export const permissionMap = new Map([
  ["dashboard.view", "View dashboard"],
  ["dashboard.edit", "Modify dashboard"],
  ["sites.view", "View sites"],
  ["sites.add", "Add sites"],
  ["sites.edit", "Edit sites"],
  ["sites.delete", "Delete sites"],
  ["clients.viewAll", "View all clients"],
  ["clients.viewPool", "View pooled clients only"],
  ["clients.viewAllExceptPool", "View all clients except pool"],
  ["clients.viewContactInformation", "View client's contact information"],
  ["clients.add", "Add clients"],
  ["clients.editAll", "Edit all client information"],
  ["clients.editCompany", "Edit company and sales information"],
  ["clients.editAccountHandling", "Edit client's owner details"],
  ["clients.editStatus", "Edit client's status"],
  ["clients.editContact", "Edit client's contact information"],
  ["clients.delete", "Delete client"],
  ["deck.view", "View deck"],
  ["deck.add", "Generate deck"],
  ["booking.viewAll", "View all bookings"],
  ["booking.viewAvailability", "View booking availability only"],
  ["booking.viewBookings", "View bookings only"],
  ["booking.add", "Create booking"],
  ["booking.update", "Edit booking details"],
  ["booking.delete", "Delete booking"],
  ["reports.viewAll", "View reports"],
  ["reports.add", "Create reports"],
  ["reports.edit", "Edit reports"],
  ["reports.delete", "Delete reports"],
  ["companies.view", "View companies"],
  ["companies.add", "Add companies"],
  ["companies.edit", "Edit companies"],
  ["companies.delete", "Delete companies"],
  ["mediums.view", "View mediums"],
  ["mediums.add", "Add mediums"],
  ["mediums.edit", "Edit mediums"],
  ["mediums.delete", "Delete mediums"],
  ["users.view", "View users"],
  ["users.add", "Add users"],
  ["users.edit", "Edit users"],
  ["users.delete", "Delete users"],
  ["roles.view", "View roles"],
  ["roles.add", "Add roles"],
  ["roles.edit", "Edit roles"],
  ["roles.delete", "Delete roles"],
  ["modules.add", "Add modules"],
  ["modules.view", "View modules"],
  ["modules.edit", "Edit modules"],
  ["modules.delete", "Delete modules"],
  ["logs.view", "View logs"],
  ["settings.view", "View settings"],
  ["contracts.view", "View contracts"],
  ["help.view", "View help"],
]);

export const companyPermissionsMap = new Map([
  ["show.all", "Show all clients"],
  ["show.pool", "Show POOL clients only"],
  ["show.other", "Show all except POOL clients"],
]);
